In [ ]:
                **** Assignment 3 *****

In [110]:
#Q1. Understanding Feature Distributions (Iris Dataset)
#Context: Before training any ML model, we analyze feature distributions.
#Dataset: Load Iris dataset from sklearn
#Tasks:
#Extract feature matrix as NumPy array
#Compute: Mean Median Standard deviation Variance (for each feature)
#Identify: Which feature has highest variability and why it matters in ML
#Convert any one feature into shape (n,1) and explain why ML models expect this format
######################################################################################

import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
iris = load_iris()

feature_matrix = iris.data
feature_names = iris.feature_names

df = pd.DataFrame(feature_matrix, columns=iris.feature_names )

#Mean Median Standard deviation Variance (for each feature)
#df.info()
print(df.describe())
#Which feature has highest variability, this one needed for better separation between classes
print(df.var())

#Convert any one feature into shape (n,1) and why ML models expect this format beacuse input format need as 2D array and output as a 1D Array
sepal_length = np.array(df['sepal length (cm)'])
print(sepal_length.reshape(-1,1))


       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4

In [128]:
#Q2. Data Selection for Model Input
#Context: Models are trained on selective features, not full raw data.
#Dataset: Iris
#Tasks:
#1. Extract: First 100 samples Only last 2 features
#2. Use boolean masking: Select samples where petal length is greater than dataset mean
#3. Count selected samples
#4. Explain how this relates to feature-based filtering in ML
#########################################################################

#Extract: First 100 samples Only last 2 features
print(df.iloc[0:100, 2:4])

mask = df['petal length (cm)'] > df['petal length (cm)'].mean()
print(df[mask])

#Count selected samples
print(len(df[mask]))

# Boolean masking need for clear unwanted data and focus on specific group data

    petal length (cm)  petal width (cm)
0                 1.4               0.2
1                 1.4               0.2
2                 1.3               0.2
3                 1.5               0.2
4                 1.4               0.2
..                ...               ...
95                4.2               1.2
96                4.2               1.3
97                4.3               1.3
98                3.0               1.1
99                4.1               1.3

[100 rows x 2 columns]
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
53                 5.5               2.3                4.0               1.3
54                 6.5               2.8                4.6               1.5
..                 ...      

In [133]:
#Q3. Feature Scaling using NumPy (Very Important)
#Context: Most ML models require normalized data.
#Dataset: Iris (NumPy array)
#Tasks:
#1. Apply standardization
#2. Verify: Mean ≈ 0 Std ≈ on

#formula [new std value = (original value - mean of a feature)/ feature standard division]

new_value = (feature_matrix - np.mean(feature_matrix)) / np.std(feature_matrix)

print('Mean:', np.mean(new_value))
print('Std:', np.std(new_value))

Mean: 1.1842378929335003e-16
Std: 1.0


In [139]:
#Q4. Dataset Understanding (Titanic Dataset)
#Context: First step in ML pipeline is dataset inspection.
#Dataset: Titanic (Seaborn)
#Tasks:
#Display: head(), tail() info(), describe()
#Identify: Missing values per column Numerical vs categorical features
#Explain: Why identifying feature types is important before modeling
####################################################################

import numpy as np
import pandas as pd
import seaborn as sns

data = sns.load_dataset("titanic")

titanic_df = data.copy()

#Display: head(), tail() info(), describe()
titanic_df.head()
titanic_df.tail()
titanic_df.info()

#Identify: Missing values per column Numerical vs categorical features
titanic_df.isnull().sum()

# we need to identify missing value for each features because we need to fill missing value with mean, midian or mode value so our ML model can predict
# correct output

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [196]:
#Q5. Filtering Data for Business Logic
#Context: Real ML problems require filtering relevant populations.
#Dataset: Titanic
#Tasks:
#1. Filter: Female passengers in 1st class
#2. Compute: Survival rate for this group
#3. Compare with overall survival rate
#4. Interpret: What insight can be used in ML feature engineering
#######################################################################

titanic_df.head()

#1. Filter: Female passengers in 1st class
female_passenger = (titanic_df['sex'] == 'female') & (titanic_df['class'].isin(['First']))
female_survive_first_class = (titanic_df['sex'] == 'female') & (titanic_df['class'].isin(['First']) & (titanic_df['survived'] == 1))
titanic_df[female_passenger]
titanic_df[female_survive_first_class]

#2. Compute: Survival rate for this group
survival_rate = (len(titanic_df[female_survive_first_class])/len(titanic_df[female_passenger])) * 100
print(survival_rate)

# This feature can provide high survival rate group

96.80851063829788


In [202]:
#Q6. Handling Missing Data (Critical ML Step)
#Context: Models cannot handle null values.
#Dataset: Titanic
#Tasks:
#1.Fill missing age using median
#2.Fill missing embarked using mode
#3.Drop deck column
#4.Explain: Why different strategies are used for different columns
####################################################################

#1.Fill missing age using median
titanic_df['age'].fillna(titanic_df['age'].median(), inplace = True)

#2.Fill missing embarked using mode
titanic_df['embarked'].fillna(titanic_df['embarked'].mode()[0], inplace = True)

#3.Drop deck column
titanic_df.drop(columns = ['deck'], inplace = True)
titanic_df.isnull().sum()

C:\Users\agayen\AppData\Local\Temp\ipykernel_4888\274654576.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_df['age'].fillna(titanic_df['age'].median(), inplace = True)


survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [212]:
#Q7. Feature Engineering for Model Improvement
#Context: Raw data is rarely useful—features must be created.
#Dataset: Titanic
#Tasks:
#Create: family_size = sibsp + parch + 1
#Create: is_alone (binary feature)
#Compute survival rate by is_alone
#Explain: Why engineered features improve ML models
###########################################################

#Create: family_size = sibsp + parch + 1
titanic_df['family_size'] = titanic_df['sibsp'] + titanic_df['parch'] + 1

#Create: is_alone (binary feature)
titanic_df['is_alone'] = titanic_df['family_size']<= 1

#Compute survival rate by is_alone

alone_data = titanic_df['is_alone']
alone_survived = (titanic_df['is_alone']) & (titanic_df['survived'])
titanic_df[alone_data]
titanic_df[alone_survived]
survival_rate_alone = (len(titanic_df[alone_survived]) / len(titanic_df[alone_data])) * 100
print(survival_rate_alone)

30.353817504655495


In [236]:
#Q8. Group-Based Insights (Customer Segmentation Logic)
#Context: ML models often depend on aggregated patterns.
#Dataset: Tips
#Tasks:
#Compute: Average tip by day Total bill by gender
#Create new feature: tip_percentage
#Identify: Which day has highest tipping behavior
#Explain: How this helps in segmentation models
###################################################

import pandas as pd
import seaborn as sns

df = sns.load_dataset('tips')
data_tips = df.copy()

#Compute: Average tip by day Total bill by gender
avg_tip_day = data_tips.groupby('day')['tip'].mean()
print('Average tip by day:\n', avg_tip_day)

total_bill_gender = data_tips.groupby('sex')['total_bill'].sum()
print('Total bill by gender:\n', total_bill_gender)

#Create new feature: tip_percentage
data_tips['tip_percentage'] = (data_tips['tip'] / data_tips['total_bill']) * 100
print(data_tips.head())

#Identify: Which day has highest tipping behavior
highest_tip_day = data_tips.groupby('day')['tip'].max()
print('highest tipping behavior:\n', highest_tip_day)

# By creating features like tip_percentage and analyzing behavior across categories (day, gender), we can uncover patterns that help segment 
#customers and improve machine learning models by providing more meaningful and normalized features.

Average tip by day:
 day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
Total bill by gender:
 sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64
   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765
highest tipping behavior:
 day
Thur     6.70
Fri      4.73
Sat     10.00
Sun      6.50
Name: tip, dtype: float64


C:\Users\agayen\AppData\Local\Temp\ipykernel_4888\662662096.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tip_day = data_tips.groupby('day')['tip'].mean()
C:\Users\agayen\AppData\Local\Temp\ipykernel_4888\662662096.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_bill_gender = data_tips.groupby('sex')['total_bill'].sum()
C:\Users\agayen\AppData\Local\Temp\ipykernel_4888\662662096.py:29: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future def

In [263]:
#Q9. Advanced Filtering + Subsetting
#Context: Training data is often filtered based on business rules.
#Dataset: Tips
#Tasks:
#Filter: total_bill > 20 AND tip < 3
#Select only relevant columns
#Analyze: Is this segment under-tipping?
#Explain: How such filtering helps anomaly detection
###############################################################

data_tips.head()

#Filter: total_bill > 20 AND tip < 3
filter_data = (data_tips['total_bill'] > 20) & (data_tips['tip'] < 3)
data_tips[filter_data]

#Select only relevant columns
data_tips.loc[filter_data, ['total_bill', 'sex', 'tip', 'day', 'tip_percentage']]

#Analyze: Is this segment under-tipping?

avg_tip_percentange = data_tips['tip_percentage'].mean()
avg_filter_data_tip_percentage = data_tips.loc[filter_data, ['tip_percentage']].mean()

print('overall tip %\n', avg_tip_percentange)
print('segment tip %\n', avg_filter_data_tip_percentage)

under_tipping = False

if avg_tip_percentange > avg_filter_data_tip_percentage['tip_percentage']:
    under_tipping = True
print(under_tipping)

overall tip %
 16.08025817225047
segment tip %
 tip_percentage    9.082753
dtype: float64
True


In [268]:
#Q10. Data Transformation for Model Input (NumPy)
#Context: ML models require structured numeric arrays.
#Tasks:
#Create two arrays of shape (3,2)
#Perform: Vertical stacking Horizontal stacking
#Reshape into (2,6)
#Explain: Why reshaping is required in ML pipelines
##############################################################

import numpy as np

arr1 = np.array([[2,4], [8,10], [12,14]])
arr2 = np.array([[1,3], [5,7], [9,11]])

v = np.vstack((arr1,arr2)).reshape(2,6)
h = np.hstack((arr1,arr2)).reshape(2,6)

print('Vertical:\n', v)
print('Horizontal:\n', h)

Vertical:
 [[ 2  4  8 10 12 14]
 [ 1  3  5  7  9 11]]
Horizontal:
 [[ 2  4  1  3  8 10]
 [ 5  7 12 14  9 11]]


In [17]:
#Q11. End-to-End ML Preprocessing Pipeline (Titanic)
#Context: Prepare dataset for ML model training
#Tasks:
#Load dataset
#Handle missing values
#Encode categorical variables (sex, embarked)
#Normalize numerical features
#Convert to NumPy array
#Output: Final feature matrix ready for model training
############################################################

import pandas as pd 
import seaborn as sns
import numpy as np

df = sns.load_dataset("titanic")

titanic_data = df.copy()

titanic_data.head()
#Handle missing values
titanic_data.fillna({
    'age': titanic_data['age'].mean(),
    'embark_town': titanic_data['embark_town'].mode()[0],
    'embarked': titanic_data['embarked'].mode()[0]
}, inplace=True)

titanic_data.drop(columns = ['deck'], inplace = True)

#Encode categorical variables (sex, embarked)
titanic_data = pd.get_dummies(df, columns=['sex', 'embarked'], drop_first=True)

#Normalize numerical features
num_cols = titanic_data.select_dtypes(include=['int64', 'float64']).columns # Indetified numeric columns
for col in num_cols:
    titanic_data[col] = (titanic_data[col] - titanic_data[col].min()) / (titanic_data[col].max() - titanic_data[col].min())

#Convert to NumPy array
titanic_data_arr = np.array(titanic_data)
#Output: Final feature matrix ready for model training
print(titanic_data_arr)

[[0.0 1.0 0.2711736617240513 ... True False True]
 [1.0 0.0 0.4722292033174164 ... False False False]
 [1.0 1.0 0.32143754712239253 ... False False True]
 ...
 [0.0 1.0 nan ... False False True]
 [1.0 0.0 0.32143754712239253 ... True False False]
 [0.0 1.0 0.39683337521990447 ... True True False]]


In [31]:
#Q12. Feature Selection using Statistical Understanding
#Context: Not all features improve model performance.
#Dataset: Iris
#Tasks:
#Compute correlation matrix
#Identify highly correlated features
#Drop redundant features
#Explain: Impact on overfitting and model performance
#########################################################

import pandas as pd 
import seaborn as sns

df = sns.load_dataset("iris")
iris_dataset = df.copy()

#Compute correlation matrix
corr_matrix = iris_dataset.select_dtypes(include=['int64', 'float64']).corr()

#Identify highly correlated features
threshold = 0.9

high_corr_feature = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > threshold:
            col1 = corr_matrix.columns[i]
            col2 = corr_matrix.columns[j]
            high_corr_feature.append((col1, col2, corr_matrix.iloc[i, j]))

print(high_corr_feature)

#Drop redundant features
to_drop = set()

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > threshold:
            colname = corr_matrix.columns[i]
            to_drop.add(colname)

df_reduced = df.drop(columns=to_drop)

print(to_drop)


[('petal_width', 'petal_length', np.float64(0.962865431402796))]
{'petal_width'}


In [42]:
#Q13. Custom Feature Transformation using apply()
#Context: Real ML requires custom logic transformation.
#Dataset: Titanic
#Tasks:
#Create age_group: Child / Adult / Senior
#Use .apply()
#Compute survival rate per group
#Interpret: Which segment has highest survival likelihood
##################################################################

import pandas as pd 
import seaborn as sns

df = sns.load_dataset("titanic")

titanic_dataset = df.copy()

#Create age_group: Child / Adult / Senior
#Use .apply()
titanic_dataset['age_group'] = titanic_dataset['age'].apply(lambda x: 'Child' if x < 18 else ('Adult' if x < 60 else 'Senior'))

#Compute survival rate per group
age_group = (titanic_dataset.groupby('age_group')['survived'].mean()) * 100
print(age_group)

age_group
Adult     38.608696
Child     53.982301
Senior    29.064039
Name: survived, dtype: float64


In [49]:
#Q14. Error Analysis Simulation (Model Evaluation Thinking)
#Context: Understanding prediction errors is key in ML.
#Tasks:
#Generate 1000 random error values using NumPy
#Compute: Mean Standard deviation
#Identify outliers: Using mean ± 2*std
#Explain: What high variance means in model performance
###############################################################

import numpy as np
#Generate 1000 random error values using NumPy
errors = np.random.normal(loc=0, scale=1, size=1000)

#Compute: Mean Standard deviation
mean_value = np.mean(errors)
std_value = np.std(errors)
print('Mean Value:', mean_value)
print('Standard deviation', std_value)

#Identify outliers: Using mean ± 2*std
upper_limit = (mean_value + 2) * std_value
lower_limit = (mean_value - 2) * std_value
print('Using mean ± 2*std\n', upper_limit, lower_limit)

Mean Value: -0.04327643391692561
Standard deviation 0.9967009230964377
Using mean ± 2*std
 1.9502681845595535 -2.036535507826197


In [63]:
#Q15. Business + ML Insight Problem (Tips Dataset)
#Context: Convert data analysis into decision-making
#Tasks:
#Create: tip_percentage
#Group by: day and time
#Identify: Highest revenue segment
#Provide: Recommendation for business strategy How ML model can use this insight
####################################################

import pandas as pd
import seaborn as sns

df = sns.load_dataset("tips")

tip_dataset = df.copy()

#Create: tip_percentage
tip_dataset['tip_percentage'] = (tip_dataset['tip'] / tip_dataset['total_bill']) * 100

#Group by: day and time and Identify: Highest revenue segment
day_time_group = tip_dataset.groupby(['day', 'time'])['total_bill'].sum().sort_values(ascending=False)

print(day_time_group)

day   time  
Sat   Dinner    1778.40
Sun   Dinner    1627.16
Thur  Lunch     1077.55
Fri   Dinner     235.96
      Lunch       89.92
Thur  Dinner      18.78
Sat   Lunch        0.00
Sun   Lunch        0.00
Name: total_bill, dtype: float64


C:\Users\agayen\AppData\Local\Temp\ipykernel_22360\1629704941.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  day_time_group = tip_dataset.groupby(['day', 'time'])['total_bill'].sum().sort_values(ascending=False)
